// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuySVHtkzT17ebFgbG0Rk3piS2Kbalu4I',
    appId: '1:84800012852:web:888be924efde51f4140061',
    messagingSenderId: '84800012852',
    projectId: 'authentication-74356',
    authDomain: 'authentication-74356.firebaseapp.com',
    storageBucket: 'authentication-74356.firebasestorage.app',
    measurementId: 'G-S3QTW5EK01',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDldE44DN153DZgCXBO4ARsIYeLf6sHJEk',
    appId: '1:84800012852:android:5359233e9c36b4cc140061',
    messagingSenderId: '84800012852',
    projectId: 'authentication-74356',
    storageBucket: 'authentication-74356.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVOG83KIAO-9YdM9VHA9jofDjZrS_u9A',
    appId: '1:84800012852:ios:4f26b17135c91cdd140061',
    messagingSenderId: '84800012852',
    projectId: 'authentication-74356',
    storageBucket: 'authentication-74356.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );
}
